package org.rfcx.companion.entity

enum class Event(val id: String) {
    LOGOUT("logout"),
    CLICK_PIN("click_pin"),
    SEE_DETAIL("see_detail"),
    DELETE_DEPLOYMENT("delete_deployment"),
    CHANGE_COORDINATES("change_coordinates"),
    CHANGE_THEME("change_theme"),
    SEND_FEEDBACK("send_feedback"),
    ADD_FEEDBACK_IMAGES("add_feedback_images"),
    SELECT_LOCATION("select_location"),
    EDIT_LOCATION("edit_location"),
    CHANGE_LOCATION("change_location"),
    CHANGE_LOCATION_GROUP("change_location_group"),
    SAVE_LOCATION("save_location"),
    PLAY_TONE("play_tone"),
    PLAY_TONE_COMPLETED("play_tone_completed"),
    RETRY_PLAY_TONE("retry_play_tone"),
    PLAY_SYNC_TONE("play_sync_tone"),
    PLAY_SYNC_TONE_COMPLETED("play_sync_tone_completed"),
    ADD_DEPLOYMENT_IMAGE("add_deployment_image"),
    CREATE_AUDIOMOTH_DEPLOYMENT("create_audiomoth_deployment"),
    CREATE_SONGMETER_DEPLOYMENT("create_songmeter_deployment"),
}
