package org.rfcx.companion.entity

enum class OfflineMapState(val key: String) {
    DELETING_STATE("DELETING_STATE"),
    DOWNLOAD_STATE("DOWNLOAD_STATE"),
    DOWNLOADED_STATE("DOWNLOADED_STATE"),
    UNAVAILABLE("UNAVAILABLE"),
    DOWNLOAD_CANCEL_STATE("DOWNLOAD_CANCEL_STATE"),
    DOWNLOADING_STATE("DOWNLOADING_STATE"),
}
