package org.rfcx.companion.entity

enum class Screen(val id: String) {
    LOGIN("Login"),
    MAP("Map"),
    PROFILE("Profile"),
    COORDINATES("Coordinates"),
    FEEDBACK("Feedback"),
    CHOOSE_DEVICE("Choose Device"),
    LOCATION("Location"),
    DETAIL_DEPLOYMENT_SITE("Detail Deployment Site"),
    PROJECT("Project"),
    AUDIO_MOTH_CHECK_LIST("AudioMoth Check List"),
    SONG_METER_CHECK_LIST("Song Meter Check List"),
    SYNC("Sync"),
    EDGE_DETAIL("Edge Detail"),
    MAP_PICKER("Map Picker"),
    EDIT_LOCATION("Edit Location"),
    MAP_SEARCH_RESULT("Map Search Result"),
    CONNECT_GUARDIAN("Connect Guardian"),
    GUARDIAN_REGISTER("Guardian Register"),
    GUARDIAN_SIGNAL("Guardian Signal"),
    GUARDIAN_SELECT_PROFILE("Guardian Select Profile"),
    GUARDIAN_CONFIGURE("Guardian Configure"),
    GUARDIAN_MICROPHONE("Guardian Microphone"),
    GUARDIAN_SOLAR_PANEL("Guardian Solar Panel"),
    GUARDIAN_CHECKIN_TEST("Guardian CheckIn Test"),
    GUARDIAN_DEPLOY("Guardian Deploy"),
    GUARDIAN_ADVANCED("Guardian Advanced"),
    GUARDIAN_DIAGNOSTIC("Guardian Diagnostic")
}
