name: CD production

on:
  workflow_dispatch:
  release:
    types: [created]

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}

jobs:
  lint-build-test:
    name: Build, Upload
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup: Clone'
        uses: actions/checkout@v1

      - name: 'Setup: JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: 'Build: Assemble APK'
        run: ./gradlew assembleInternalRelease
        
      - uses: r0adkll/sign-android-release@v1
        name: 'Sign an APK'
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/internal/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_STORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "30.0.2"
          
      - name: 'Upload a Signed APK'
        uses: actions/upload-artifact@v3.0.0
        with:
          name: companion-production
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          
      - name: 'Upload Signed APK to Slack'
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_ALERT_COREDT_WEBHOOK }}
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          channel: build-guardians
          initial_comment: 'test message'
