name: CD

on:
  push:
    branches:
      - staging

jobs:
  lint-build-test:
    name: Lint, Test, Assemble
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup: Clone'
        uses: actions/checkout@v1

      - name: 'Setup: JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: 'Lint: Kotlin'
        run: ./gradlew ktlintCheck

      - name: 'Lint: Kotlin (results)'
        uses: yutailang0119/action-ktlint@da5f7a6cd94a306fde4de601a417c368975d8c93
        with:
          report-path: app/build/reports/ktlint/*.xml
        continue-on-error: false

      - name: 'Lint: Android'
        run: ./gradlew lintInternalDevelopDebug
        
      - name: 'Build: Assemble Staging APK'
        run: ./gradlew assembleInternalDevelopDebug
        
      - name: Upload a Build APK
        uses: actions/upload-artifact@v3.0.0
        with:
          name: my-artifact
          path: app/build/output/internalDevelop/debug/app-internalDevelop-debug.apk
