name: CD

on:
  push:
    branches:
      - develop

jobs:
  lint-build-test:
    name: Build, Upload
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup: Clone'
        uses: actions/checkout@v1

      - name: 'Setup: JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
        
      - name: 'Build: Assemble Staging APK'
        run: ./gradlew assembleInternalDevelopDebug
        
      - name: Upload a Build APK
        uses: actions/upload-artifact@v3.0.0
        with:
          name: my-artifact
          path: app/build/output/internalDevelop/debug/app-internalDevelop-debug.apk
